const fs=require("fs"),path=require("path");
const root=path.resolve(__dirname,".."),cabinetsPath=path.join(root,"arcade/cabinets.json");
const idOk=/^[a-z0-9]+(?:-[a-z0-9]+)*$/,genres=new Set(["survival","racer","platformer","puzzle","strategy"]);
const read=p=>JSON.parse(fs.readFileSync(p,"utf8"));
function assertSpec(s){if(s.schema!=="portal.game-factory.spec.v1")throw Error("bad schema");if(!idOk.test(s.id||""))throw Error("bad id");for(const k of ["title","tagline","worldKey","artifact"])if(!s[k])throw Error("missing "+k);if(!genres.has(s.genre))throw Error("unsupported genre: "+s.genre);if(!Number.isInteger(s.durationSeconds)||s.durationSeconds<10||s.durationSeconds>300)throw Error("durationSeconds 10..300")}
const shell=(s,body)=>`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${s.title}</title><style>*{box-sizing:border-box}body{margin:0;background:#07090d;color:#f4f7ff;font-family:ui-monospace;overflow:hidden}canvas{width:100vw;height:100svh;display:block}header{position:fixed;inset:12px 14px auto;display:flex;justify-content:space-between;font-size:10px;letter-spacing:.12em;z-index:2}a{color:inherit;text-decoration:none}.gate{position:fixed;inset:0;display:grid;place-items:center;text-align:center;background:#05070bea;z-index:3}.hidden{display:none}button{padding:12px 18px;border:1px solid #71809b;background:#0b1019;color:#fff;border-radius:999px}</style></head><body><header><a href="../../arcade/">← ARCADE</a><span id="hud"></span></header><canvas></canvas><div class="gate" id="gate"><div><small>${s.tagline}</small><h1>${s.title}</h1><button id="start">START</button></div></div><script type="module">import{beginRun,event,finishRun}from"../protocol.js";import{grantArtifact}from"../state.js";const SPEC=${JSON.stringify(s)};${body}</script></body></html>`;
const common=`const c=document.querySelector("canvas"),x=c.getContext("2d"),gate=document.querySelector("#gate"),hud=document.querySelector("#hud");let run,start,last,done=false,keys=new Set;function size(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio}addEventListener("resize",size);size();addEventListener("keydown",e=>keys.add(e.key));addEventListener("keyup",e=>keys.delete(e.key));function end(result,extra={}){if(done)return;done=true;if(result==="clear")grantArtifact(SPEC.artifact);finishRun(run,{result,artifact:result==="clear"?SPEC.artifact:null,...extra});gate.classList.remove("hidden");gate.innerHTML='<div><small>'+SPEC.title+'</small><h1>'+(result==="clear"?"CLEAR":"TRY AGAIN")+'</h1><button onclick="location.reload()">AGAIN</button></div>'}function boot(frame){document.querySelector("#start").onclick=()=>{run=beginRun(SPEC.id);event(run,"factory-game-start",{schema:SPEC.schema,genre:SPEC.genre});gate.classList.add("hidden");start=last=performance.now();requestAnimationFrame(frame)}}`;
function survival(s){return shell(s,common+`let p={x:.5,y:.8},haz=[];c.addEventListener("pointermove",e=>{p.x=e.clientX/innerWidth;p.y=e.clientY/innerHeight});function frame(t){if(done)return;const dt=Math.min(.04,(t-last)/1000||0);last=t;if(keys.has("ArrowLeft")||keys.has("a"))p.x-=dt*.55;if(keys.has("ArrowRight")||keys.has("d"))p.x+=dt*.55;if(keys.has("ArrowUp")||keys.has("w"))p.y-=dt*.55;if(keys.has("ArrowDown")||keys.has("s"))p.y+=dt*.55;p.x=Math.max(.03,Math.min(.97,p.x));p.y=Math.max(.03,Math.min(.97,p.y));if(Math.random()<dt*3.2)haz.push({x:Math.random(),y:-.04,v:.18+Math.random()*.28,r:.02});haz.forEach(h=>h.y+=h.v*dt);haz=haz.filter(h=>h.y<1.1);for(const h of haz)if(Math.hypot(h.x-p.x,h.y-p.y)<h.r+.022){event(run,"collision");return end("lost")}const left=Math.max(0,SPEC.durationSeconds-(t-start)/1000);hud.textContent="HOLD "+left.toFixed(1)+"s";x.clearRect(0,0,c.width,c.height);x.save();x.scale(c.width,c.height);x.fillStyle="#dce8ff";x.beginPath();x.arc(p.x,p.y,.022,0,7);x.fill();x.fillStyle="#ff6f91";for(const h of haz){x.beginPath();x.arc(h.x,h.y,h.r,0,7);x.fill()}x.restore();if(left<=0)return end("clear");requestAnimationFrame(frame)}boot(frame);`)}
function racer(s){return shell(s,common+`let lane=1,distance=0,obs=[];addEventListener("keydown",e=>{if(e.key==="ArrowLeft")lane=Math.max(0,lane-1);if(e.key==="ArrowRight")lane=Math.min(2,lane+1)});c.addEventListener("pointerdown",e=>lane=e.clientX<innerWidth/2?Math.max(0,lane-1):Math.min(2,lane+1));function frame(t){if(done)return;const dt=Math.min(.04,(t-last)/1000||0);last=t;distance+=dt;if(Math.random()<dt*1.4)obs.push({lane:Math.floor(Math.random()*3),y:-.1});obs.forEach(o=>o.y+=dt*.65);for(const o of obs)if(o.lane===lane&&o.y>.76&&o.y<.92){event(run,"gate-hit",{lane});return end("lost",{distance})}obs=obs.filter(o=>o.y<1.1);const left=Math.max(0,SPEC.durationSeconds-distance);hud.textContent="RUN "+left.toFixed(1)+"s";x.clearRect(0,0,c.width,c.height);x.save();x.scale(c.width,c.height);x.fillStyle="#dce8ff";x.fillRect(.17+lane*.28,.82,.1,.06);x.fillStyle="#ffb45e";for(const o of obs)x.fillRect(.17+o.lane*.28,o.y,.1,.04);x.restore();if(left<=0)return end("clear",{distance});requestAnimationFrame(frame)}boot(frame);`)}
function platformer(s){return shell(s,common+`let p={x:.12,y:.75,vy:0},goal=.88;function jump(){if(p.y>=.749)p.vy=-.65}addEventListener("keydown",e=>{if(e.key===" "||e.key==="ArrowUp")jump()});c.addEventListener("pointerdown",jump);function frame(t){if(done)return;const dt=Math.min(.04,(t-last)/1000||0);last=t;if(keys.has("ArrowRight")||keys.has("d"))p.x+=dt*.22;if(keys.has("ArrowLeft")||keys.has("a"))p.x-=dt*.18;p.vy+=dt*1.7;p.y+=p.vy*dt;if(p.y>.75){p.y=.75;p.vy=0}p.x=Math.max(.04,Math.min(.94,p.x));hud.textContent="REACH THE BEACON";x.clearRect(0,0,c.width,c.height);x.save();x.scale(c.width,c.height);x.fillStyle="#58677d";x.fillRect(0,.8,1,.02);x.fillStyle="#dce8ff";x.fillRect(p.x,p.y,.035,.05);x.fillStyle="#78f0b0";x.fillRect(goal,.69,.025,.11);x.restore();if(p.x>=goal-.03)return end("clear",{elapsed:(t-start)/1000});if((t-start)/1000>SPEC.durationSeconds)return end("lost");requestAnimationFrame(frame)}boot(frame);`)}
function puzzle(s){return shell(s,common+`const target=[0,1,2,3],seq=[];function press(n){if(done)return;seq.push(n);event(run,"puzzle-input",{n,step:seq.length});if(n!==target[seq.length-1])return end("lost",{moves:seq.length});if(seq.length===target.length)return end("clear",{moves:seq.length});draw()}function draw(){hud.textContent="SEQUENCE "+seq.length+"/4";x.clearRect(0,0,c.width,c.height);x.save();x.scale(c.width,c.height);for(let i=0;i<4;i++){x.fillStyle=i<seq.length?"#78f0b0":"#5f6d86";x.fillRect(.1+i*.22,.42,.16,.16);x.fillStyle="#071019";x.font=".05px sans-serif"}x.restore()}c.addEventListener("pointerdown",e=>press(Math.max(0,Math.min(3,Math.floor((e.clientX/innerWidth-.1)/.22)))));addEventListener("keydown",e=>{const n=Number(e.key)-1;if(n>=0&&n<4)press(n)});function frame(){draw()}boot(frame);`)}
function strategy(s){return shell(s,common+`let energy=5,nodes=[0,0,0],turns=0;function act(i){if(done||energy<1)return;nodes[i]++;energy--;turns++;event(run,"strategy-action",{node:i,energy,turns});if(nodes.every(n=>n>=1))return end("clear",{turns,energy});if(energy===0)return end("lost",{turns});draw()}function draw(){hud.textContent="ENERGY "+energy+" // CONTROL ALL 3";x.clearRect(0,0,c.width,c.height);x.save();x.scale(c.width,c.height);for(let i=0;i<3;i++){x.fillStyle=nodes[i]?"#78f0b0":"#69758b";x.beginPath();x.arc(.25+i*.25,.5,.07,0,7);x.fill()}x.restore()}c.addEventListener("pointerdown",e=>act(Math.max(0,Math.min(2,Math.floor(e.clientX/innerWidth*3)))));addEventListener("keydown",e=>{const n=Number(e.key)-1;if(n>=0&&n<3)act(n)});function frame(){draw()}boot(frame);`)}
const templates={survival,racer,platformer,puzzle,strategy};
function html(s){return templates[s.genre](s)}
function validate(){const c=read(cabinetsPath),errs=[],ids=new Set;for(const g of c.cabinets){if(ids.has(g.id))errs.push(g.id+": duplicate cabinet id");ids.add(g.id);if(g.href&&g.href.startsWith("../games/")){const f=path.join(root,g.href.replace("../",""),"index.html");if(!fs.existsSync(f))errs.push(g.id+": missing "+path.relative(root,f));else{const t=fs.readFileSync(f,"utf8");if(!t.includes("beginRun")||!t.includes("finishRun"))errs.push(g.id+": missing run protocol");if(!t.includes('href="../../arcade/"'))errs.push(g.id+": missing arcade return seam")}}}if(errs.length)throw Error(errs.join("\n"));console.log("Game Factory validation passed:",c.cabinets.filter(x=>x.status==="playable").length,"playable cabinets;",genres.size,"factory genres")}
function selftest(){for(const genre of genres){const s={schema:"portal.game-factory.spec.v1",id:"factory-test-"+genre,title:"TEST "+genre.toUpperCase(),tagline:"FACTORY SELF TEST",genre,durationSeconds:30,worldKey:"portal-game-history",artifact:"test-"+genre};assertSpec(s);const a=html(s),b=html(s);if(a!==b)throw Error(genre+": nondeterministic generation");for(const seam of ["beginRun","event(run","finishRun","grantArtifact","factory-game-start"])if(!a.includes(seam))throw Error(genre+": missing "+seam)}console.log("Game Factory self-test passed:",genres.size,"genres")}
if(process.argv[2]==="--validate"){validate();return selftest()}
const input=process.argv[2];if(!input)throw Error("usage: node game-factory/game-factory.cjs <spec.json> | --validate");
const s=read(path.resolve(input));assertSpec(s);const dir=path.join(root,"games",s.id),out=path.join(dir,"index.html");if(fs.existsSync(out)&&!s.overwrite)throw Error("refusing overwrite: "+path.relative(root,out));fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(out,html(s));const c=read(cabinetsPath);if(!c.cabinets.some(x=>x.id===s.id)){c.cabinets.push({id:s.id,title:s.title,kind:"factory-game",status:"candidate",href:"../games/"+s.id+"/",tagline:s.tagline,world_key:s.worldKey});fs.writeFileSync(cabinetsPath,JSON.stringify(c,null,2)+"\n")}console.log("Generated",s.id,"["+s.genre+"]");validate();
