import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createWallet} from './wallet-crypto.mjs';
test('guided UI protects setup, pending transfers and message review',async()=>{
 const html=await readFile(new URL('./no-server.html',import.meta.url),'utf8');
 const elements=new Map([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],{value:'',textContent:'',checked:false,hidden:false,disabled:false,files:[],scrollIntoView(){}}]));
 const $=id=>elements.get(id);const data=new Map();let shared;
 globalThis.document={getElementById:$,querySelector:()=>({hidden:false}),addEventListener(){}};
 globalThis.localStorage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};
 globalThis.isSecureContext=true;globalThis.confirm=()=>true;
 Object.defineProperty(globalThis,'navigator',{value:{share:async x=>{shared=x.text;},clipboard:{writeText:async x=>{shared=x;}}},configurable:true});
 const timer=globalThis.setTimeout;globalThis.setTimeout=(f,n)=>{const t=timer(f,n);t.unref();return t;};
 await import('./no-server.mjs');
 assert.equal($('send-panel').hidden,true);
 $('password').value='Disposable-test-password-only';await $('create').onclick();
 assert.equal($('next-title').textContent,'Save your private backup');
 assert.equal($('connect-panel').hidden,true);
 $('backed').checked=true;await $('backed').onchange();
 assert.equal(JSON.parse(data.get('earthchain.no-server.v1')).backupConfirmed,true);
 await $('share-address').onclick();assert.match(shared,/^ec_[a-f0-9]+$/);
 const peer=await createWallet('Another-disposable-test-password');$('friend').value=peer.address;
 await $('session').onclick();assert.equal($('next-title').textContent,'Get your first test points');
 await $('faucet').onclick();assert.equal($('next-title').textContent,'Waiting for your friend');
 assert.equal($('propose').disabled,true);
 await $('share').onclick();const message=JSON.parse(shared);assert.equal(message.proposal.message.action.amount,100);assert.equal('vault' in message,false);
 $('incoming').value='{"schema":"private-backup"}';await $('inspect').onclick();assert.equal($('accept').disabled,true);
 $('lock').onclick();assert.equal($('next-title').textContent,'Unlock on this phone');assert.equal($('propose').disabled,true);
 globalThis.setTimeout=timer;
});
