export async function xrCapabilities(nav=globalThis.navigator){const xr=nav?.xr;if(!xr)return{webxr:false,vr:false,ar:false};const support=async mode=>{try{return await xr.isSessionSupported(mode)}catch{return false}};const [vr,ar]=await Promise.all([support("immersive-vr"),support("immersive-ar")]);return{webxr:true,vr,ar}}
export function comfortSettings(input={}){return{locomotion:input.locomotion==="smooth"?"smooth":"teleport",turn:input.turn==="smooth"?"smooth":"snap",snapDegrees:Math.max(15,Math.min(90,Number(input.snapDegrees)||30)),vignette:input.vignette!==false,seated:Boolean(input.seated)}}
export function xrInputState(){return{head:null,left:null,right:null,hands:{left:null,right:null},select:{left:false,right:false}}}
export function poseToPoint(pose){const p=pose?.transform?.position;return p?{x:p.x,y:p.y,z:p.z}:null}
export function spatialAnchor({id,x=0,y=0,z=0}={}){return{id:id||"anchor",position:{x,y,z},persistent:false}}

export function interactionTarget(objects=[],point,maxDistance=.25){let best=null,d=maxDistance;for(const o of objects){const p=o.position||o,dx=p.x-point.x,dy=p.y-point.y,dz=(p.z||0)-(point.z||0),n=Math.hypot(dx,dy,dz);if(n<=d){d=n;best=o}}return best}
export function grabState(){let held=null;return{get held(){return held},grab(object){if(held||!object)return false;held=object;return true},release(){const out=held;held=null;return out}}}
export async function requestXRSession(mode="immersive-vr",options={optionalFeatures:["local-floor","bounded-floor"]},nav=globalThis.navigator){if(!nav?.xr?.requestSession)throw Error("WebXR unavailable");return nav.xr.requestSession(mode,options)}

export async function referenceSpace(session,preferred=["local-floor","local","viewer"]){for(const type of preferred){try{return{type,space:await session.requestReferenceSpace(type)}}catch{}}throw Error("No XR reference space available")}
export function controllerRegistry(){const map=new Map;return{sync(session){const seen=new Set;for(const source of session.inputSources||[]){const hand=source.handedness||"none";seen.add(hand);if(!map.has(hand))map.set(hand,{hand,source,grip:null,ray:null,selecting:false});else map.get(hand).source=source}for(const k of [...map.keys()])if(!seen.has(k))map.delete(k);return[...map.values()]},get:hand=>map.get(hand)||null,all:()=>[...map.values()]}}
export function updateControllerPoses(registry,frame,space){for(const c of registry.all()){if(c.source.gripSpace){const p=frame.getPose(c.source.gripSpace,space);c.grip=poseToPoint(p)}if(c.source.targetRaySpace){const p=frame.getPose(c.source.targetRaySpace,space);c.ray=poseToPoint(p)}}return registry.all()}
export function teleportTarget(origin,direction,{distance=2,floorY=0}={}){const m=Math.hypot(direction.x,direction.z)||1;return{x:origin.x+direction.x/m*distance,y:floorY,z:origin.z+direction.z/m*distance}}
export function bindSelect(session,registry,{onStart,onEnd}={}){const start=e=>{const h=e.inputSource?.handedness||"none",c=registry.get(h);if(c)c.selecting=true;if(onStart)onStart(h,c,e)};const end=e=>{const h=e.inputSource?.handedness||"none",c=registry.get(h);if(c)c.selecting=false;if(onEnd)onEnd(h,c,e)};session.addEventListener("selectstart",start);session.addEventListener("selectend",end);return()=>{session.removeEventListener("selectstart",start);session.removeEventListener("selectend",end)}}
