export async function xrCapabilities(nav=globalThis.navigator){const xr=nav?.xr;if(!xr)return{webxr:false,vr:false,ar:false};const support=async mode=>{try{return await xr.isSessionSupported(mode)}catch{return false}};const [vr,ar]=await Promise.all([support("immersive-vr"),support("immersive-ar")]);return{webxr:true,vr,ar}}
export function comfortSettings(input={}){return{locomotion:input.locomotion==="smooth"?"smooth":"teleport",turn:input.turn==="smooth"?"smooth":"snap",snapDegrees:Math.max(15,Math.min(90,Number(input.snapDegrees)||30)),vignette:input.vignette!==false,seated:Boolean(input.seated)}}
export function xrInputState(){return{head:null,left:null,right:null,hands:{left:null,right:null},select:{left:false,right:false}}}
export function poseToPoint(pose){const p=pose?.transform?.position;return p?{x:p.x,y:p.y,z:p.z}:null}
export function spatialAnchor({id,x=0,y=0,z=0}={}){return{id:id||"anchor",position:{x,y,z},persistent:false}}

export function interactionTarget(objects=[],point,maxDistance=.25){let best=null,d=maxDistance;for(const o of objects){const p=o.position||o,dx=p.x-point.x,dy=p.y-point.y,dz=(p.z||0)-(point.z||0),n=Math.hypot(dx,dy,dz);if(n<=d){d=n;best=o}}return best}
export function grabState(){let held=null;return{get held(){return held},grab(object){if(held||!object)return false;held=object;return true},release(){const out=held;held=null;return out}}}
export async function requestXRSession(mode="immersive-vr",options={optionalFeatures:["local-floor","bounded-floor"]},nav=globalThis.navigator){if(!nav?.xr?.requestSession)throw Error("WebXR unavailable");return nav.xr.requestSession(mode,options)}

export async function referenceSpace(session,preferred=["local-floor","local","viewer"]){for(const type of preferred){try{return{type,space:await session.requestReferenceSpace(type)}}catch{}}throw Error("No XR reference space available")}
export function controllerRegistry(){const map=new Map;return{sync(session){const seen=new Set;for(const source of session.inputSources||[]){const hand=source.handedness||"none";seen.add(hand);if(!map.has(hand))map.set(hand,{hand,source,grip:null,ray:null,selecting:false});else map.get(hand).source=source}for(const k of [...map.keys()])if(!seen.has(k))map.delete(k);return[...map.values()]},get:hand=>map.get(hand)||null,all:()=>[...map.values()]}}
export function updateControllerPoses(registry,frame,space){for(const c of registry.all()){if(c.source.gripSpace){const p=frame.getPose(c.source.gripSpace,space);c.grip=poseToPoint(p)}if(c.source.targetRaySpace){const p=frame.getPose(c.source.targetRaySpace,space);c.ray=poseToPoint(p)}}return registry.all()}
export function teleportTarget(origin,direction,{distance=2,floorY=0}={}){const m=Math.hypot(direction.x,direction.z)||1;return{x:origin.x+direction.x/m*distance,y:floorY,z:origin.z+direction.z/m*distance}}
export function bindSelect(session,registry,{onStart,onEnd}={}){const start=e=>{const h=e.inputSource?.handedness||"none",c=registry.get(h);if(c)c.selecting=true;if(onStart)onStart(h,c,e)};const end=e=>{const h=e.inputSource?.handedness||"none",c=registry.get(h);if(c)c.selecting=false;if(onEnd)onEnd(h,c,e)};session.addEventListener("selectstart",start);session.addEventListener("selectend",end);return()=>{session.removeEventListener("selectstart",start);session.removeEventListener("selectend",end)}}

export function xrWorldObject({id,x=0,y=1,z=-2,scale=.12,color=[.4,.8,1],grabbable=true}={}){return{id:id||"object",position:{x,y,z},scale,color,grabbable,heldBy:null}}
export function nearestXRObject(objects=[],point,maxDistance=.3){if(!point)return null;return interactionTarget(objects.filter(o=>o.grabbable!==false),point,maxDistance)}
export function controllerGrabSystem(objects=[]){const held=new Map;return{start(hand,point){if(held.has(hand))return held.get(hand);const o=nearestXRObject(objects,point);if(!o||o.heldBy)return null;o.heldBy=hand;held.set(hand,o);return o},update(hand,point){const o=held.get(hand);if(o&&point)o.position={...point};return o||null},end(hand){const o=held.get(hand)||null;if(o)o.heldBy=null;held.delete(hand);return o},held:hand=>held.get(hand)||null}}
export function locomotionState(){let offset={x:0,y:0,z:0};return{get offset(){return{...offset}},teleport(target){if(!target)return false;offset={x:target.x,y:target.y,z:target.z};return true},apply(point){return point?{x:point.x-offset.x,y:point.y-offset.y,z:point.z-offset.z}:null},reset(){offset={x:0,y:0,z:0}}}}

export function teleportArc(origin,velocity,{gravity=-9.8,steps=20,dt=.05,floorY=0,maxDistance=6}={}){const points=[],v={...velocity};let p={...origin},valid=false;for(let i=0;i<steps;i++){p={x:p.x+v.x*dt,y:p.y+v.y*dt,z:p.z+v.z*dt};v.y+=gravity*dt;const dx=p.x-origin.x,dz=p.z-origin.z;if(Math.hypot(dx,dz)>maxDistance)break;points.push({...p});if(p.y<=floorY){p.y=floorY;points[points.length-1]={...p};valid=true;break}}return{points,target:valid?points[points.length-1]:null,valid}}
export function comfortTeleport({maxDistance=6,minDistance=.25}={}){return{validate(origin,target){if(!origin||!target)return false;const d=Math.hypot(target.x-origin.x,target.z-origin.z);return d>=minDistance&&d<=maxDistance&&Math.abs(target.y)<=.15}}}
